.TH man 1 "_simple-shell man page"
.SH NAME
_simple-shell
.SH SYNOPSIS
.B it is a thompson shell but simpler.
.br
.B int _simple-shell(placeholder)
.SH DESCRIPTION
.PP
_simple-shell is a simple shell.
.PP
This shell can handle the following commands
.br
chmod -
.br
pwd -
.br
cat -
.br
cd -
.br
ls - 
.SH "RETURN VALUE"
_simple_shell returns the result of the command you provide it.