.TH man 1 "_simple-shell man page"
.SH NAME
simple-shell
.SH SYNOPSIS
.B command [OPTION]... [FILE]...
.br
.SH DESCRIPTION
.PP
hsh is a simple shell written in C. It takes command inputs from the user, verifies if the input is correct, and passes them to the machine to execute through the kernel.
.br
.SH OPTIONS
.PP
N/A
.br
.SH COMMANDS
.PP
The shell can handle the following commands.
.br
cat - concatenates and prints file contents.
.br
cd - changes directory.
.br
ctrl + c - the line discipline of your terminal sends SIGINT to processes in the foreground process group.
.br
ctrl + d - tells the bash session to end.
.br
echo - displays a line of text
.br
ls - lists contents of working directory. [-l, -a, -s]
.br
man - gives a manual entry for specified command or function.
.br
mkdir - makes a directory of specified name at current or specified location.
.br
mv - renames or moves a file to specified location.
.br
pwd - prints working directory.
.br
rm - removes files or directories.
.br
rmdir - removes a directory of specified name at current or specified location.
.br
touch - makes a file of specified name
.br
.SH "RETURN VALUE"
.B hsh returns the result of the command you provide it.
.br
.SH BUGS
.PP
Errors with whitespaces in command line.
.br
.SH HISTORY
.PP
Version 1.0.0
.br
